# Generated by Django 3.0.5 on 2020-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('slug', models.CharField(default='', max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
