# Generated by Django 3.0.5 on 2020-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEditor',
            fields=[
                ('editor_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=25)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
