# Generated by Django 3.0.5 on 2020-07-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200717_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogEditor',
        ),
    ]
