# Generated by Django 3.0.5 on 2020-06-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cartItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
            ],
        ),
    ]
