# Generated by Django 3.0.5 on 2020-07-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200629_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
