# Generated by Django 3.0.5 on 2020-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_priceperitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('optPhone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('zip', models.CharField(default='', max_length=6)),
                ('landmark', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
