# Generated by Django 3.0.5 on 2020-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200703_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('optPhone', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('zip', models.CharField(default='', max_length=6)),
                ('landmark', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='optPhone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip',
        ),
    ]
