# Generated by Django 3.0.5 on 2020-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200703_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
