# Generated by Django 3.0.5 on 2020-07-06 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200705_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 11, 17, 30, 153767)),
        ),
    ]
